services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LeadingSystems\ContaoSchedulerBundle\Display\Common\Helper\Helper:
    public: true
    autowire: false

  LeadingSystems\ContaoSchedulerBundle\Cronjob\CronDispatcher:
    arguments:
      - '@LeadingSystems\ContaoSchedulerBundle\SchedulerDispatcher'
    tags:
      - { name: contao.cronjob, interval: minutely, method: dispatchScheduler }

  LeadingSystems\ContaoSchedulerBundle\SchedulerDispatcher:
    # must only be public during development so that it can be used in apiResource_hotwireSchedulerDispatcher
    public: true
    arguments:
      - !tagged_iterator ls_scheduler.schedulable

  LeadingSystems\ContaoSchedulerBundle\Helpers\DCACallbackHelper:
    arguments:
      - !tagged_iterator ls_scheduler.schedulable
      - '@database_connection'
      - '@service_container'
    tags:
      - { name: contao.callback, table: tl_ls_scheduler_job, target: fields.scriptToExecute.options, method: getScriptsForSchedulerExecutionAsOptions }
      - { name: contao.callback, table: tl_ls_scheduler_job, target: fields.cronExpression.save, method: cronExpressionBackendFieldValidation }
      - { name: contao.callback, table: tl_ls_scheduler_job, target: list.label.label, method: getSchedulerJobBackendListLabel }
      - { name: contao.callback, table: tl_ls_scheduler_job, target: config.onload, method: modifyPalette }

  # Schedulable services -->
  LeadingSystems\ContaoSchedulerBundle\Dummy\DummySchedulable:
    tags:
      - { name: ls_scheduler.schedulable }
